# My secrets
# remember to put in .gitignore
[db_credentials]
username = "my_username"
password = "my_password"

# .streamlit/secrets.toml
OPENAI_API_KEY = "YOUR_API_KEY"

# Use them
# Verbose version
#my_db.connect(username=st.secrets.db_credentials.username, password=st.secrets.db_credentials.password)

#
# Far more compact version!
#my_db.connect(**st.secrets.db_credentials)


#Example of accessing them
import streamlit as st
import os

# Everything is accessible via the st.secrets dict:
st.write("DB username:", st.secrets["db_username"])
st.write("DB password:", st.secrets["db_password"])